CREATE TABLE IF NOT EXISTS standup_venues (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT '',
  address varchar(500) NOT NULL DEFAULT '',
  latitude DECIMAL(10,7) DEFAULT NULL,
  longitude DECIMAL(10,7) DEFAULT NULL,
  stations json NOT NULL DEFAULT (JSON_ARRAY()),
  instagram varchar(255) NOT NULL DEFAULT '',
  tiktok varchar(255) NOT NULL DEFAULT '',
  youtube varchar(255) NOT NULL DEFAULT '',
  x varchar(255) NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT (''),
  message_for_comedian TEXT NOT NULL DEFAULT (''),
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);